spring.application.name=spendfy
server.port=8080
server.servlet.context-path=/

spring.datasource.url=jdbc:postgresql://localhost:5432/spendfy_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

app.jwtSecret=mySuperSecretKeyForSpendFyApplicationThatMustBeLongEnoughForHS512Algorithm
app.jwtExpirationInMs=864000000

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

logging.level.root=INFO
logging.level.br.com.ufape.spendfy=DEBUG
